"""Tests for the HTML audit report generator."""

from __future__ import annotations

from dont_track_me.core.base import AuditResult, Finding, ThreatLevel
from dont_track_me.core.report import generate_html_report


def _make_finding(
    title: str = "Test Finding",
    description: str = "A test finding",
    threat_level: ThreatLevel = ThreatLevel.MEDIUM,
    remediation: str = "Fix this",
) -> Finding:
    return Finding(
        title=title,
        description=description,
        threat_level=threat_level,
        remediation=remediation,
    )


def _make_result(
    module_name: str = "test_module",
    score: int = 75,
    findings: list[Finding] | None = None,
) -> AuditResult:
    return AuditResult(
        module_name=module_name,
        score=score,
        findings=findings or [],
        raw_data={},
    )


class TestHtmlStructure:
    """Basic HTML document structure."""

    def test_returns_valid_html_structure(self):
        html = generate_html_report([], 100.0)
        assert "<!DOCTYPE html>" in html
        assert "<html" in html
        assert "<head>" in html
        assert "<body>" in html
        assert "</html>" in html

    def test_contains_title(self):
        html = generate_html_report([], 80.0)
        assert "Privacy Audit Report" in html

    def test_contains_responsive_viewport(self):
        html = generate_html_report([], 80.0)
        assert "viewport" in html

    def test_contains_dark_mode_css(self):
        html = generate_html_report([], 80.0)
        assert "prefers-color-scheme: dark" in html

    def test_contains_print_css(self):
        html = generate_html_report([], 80.0)
        assert "@media print" in html

    def test_contains_script(self):
        html = generate_html_report([], 80.0)
        assert "<script>" in html
        assert "showPage" in html


class TestOverviewPage:
    """Overview page with score and module grid."""

    def test_overview_is_active_by_default(self):
        html = generate_html_report([], 80.0)
        assert 'id="overview"' in html
        assert 'class="page active"' in html

    def test_contains_overall_score(self):
        html = generate_html_report([], 73.0)
        assert ">73<" in html

    def test_contains_score_label(self):
        html = generate_html_report([], 95.0)
        assert "Excellent" in html

    def test_contains_timestamp(self):
        html = generate_html_report([], 80.0)
        assert "UTC" in html

    def test_contains_footer(self):
        html = generate_html_report([], 80.0)
        assert "Generated by dont-track-me" in html

    def test_contains_module_names_in_grid(self):
        results = [
            _make_result("dns", 80),
            _make_result("headers", 60),
        ]
        html = generate_html_report(results, 70.0)
        assert "dns" in html
        assert "headers" in html

    def test_contains_module_scores_in_grid(self):
        results = [_make_result("dns", 82)]
        html = generate_html_report(results, 82.0)
        assert "82/100" in html

    def test_grid_cards_are_clickable(self):
        results = [_make_result("dns", 80)]
        html = generate_html_report(results, 80.0)
        assert "onclick=" in html
        assert "showPage" in html

    def test_progress_bar_width_matches_score(self):
        results = [_make_result("dns", 67)]
        html = generate_html_report(results, 67.0)
        assert "width:67%" in html

    def test_multiple_modules_sorted_by_score(self):
        results = [
            _make_result("good_module", 90),
            _make_result("bad_module", 30),
            _make_result("ok_module", 60),
        ]
        html = generate_html_report(results, 60.0)
        # Worst score first in grid
        bad_pos = html.index("bad_module")
        ok_pos = html.index("ok_module")
        good_pos = html.index("good_module")
        assert bad_pos < ok_pos < good_pos

    def test_score_rounding(self):
        html = generate_html_report([], 73.6)
        assert ">74<" in html

    def test_empty_results(self):
        html = generate_html_report([], 0.0)
        assert "<!DOCTYPE html>" in html
        assert "Privacy Audit Report" in html


class TestModulePages:
    """Per-module detail pages."""

    def test_each_module_has_its_own_page(self):
        results = [
            _make_result("dns", 80),
            _make_result("headers", 60),
        ]
        html = generate_html_report(results, 70.0)
        assert 'id="mod-dns"' in html
        assert 'id="mod-headers"' in html

    def test_module_pages_hidden_by_default(self):
        results = [_make_result("dns", 80)]
        html = generate_html_report(results, 80.0)
        # Module pages have class="page" (no "active")
        assert 'class="page" id="mod-dns"' in html

    def test_back_link_to_overview(self):
        results = [_make_result("dns", 80)]
        html = generate_html_report(results, 80.0)
        assert "Back to overview" in html
        assert "showPage('overview')" in html

    def test_module_page_shows_score(self):
        results = [_make_result("dns", 82)]
        html = generate_html_report(results, 82.0)
        # Score appears in the module score ring
        assert ">82<" in html

    def test_module_page_shows_label(self):
        results = [_make_result("dns", 95)]
        html = generate_html_report(results, 95.0)
        assert "Excellent" in html

    def test_contains_finding_titles(self):
        finding = _make_finding(title="DNS Leak Detected")
        results = [_make_result("dns", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert "DNS Leak Detected" in html

    def test_contains_finding_descriptions(self):
        finding = _make_finding(description="Your DNS queries are leaking")
        results = [_make_result("dns", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert "Your DNS queries are leaking" in html

    def test_contains_finding_remediation(self):
        finding = _make_finding(remediation="Use encrypted DNS")
        results = [_make_result("dns", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert "Use encrypted DNS" in html

    def test_no_findings_message(self):
        results = [_make_result("dns", 100, [])]
        html = generate_html_report(results, 100.0)
        assert "No issues found" in html

    def test_findings_count_singular(self):
        findings = [_make_finding()]
        results = [_make_result("dns", 70, findings)]
        html = generate_html_report(results, 70.0)
        assert "1 finding" in html

    def test_findings_count_plural(self):
        findings = [_make_finding(), _make_finding(title="Second")]
        results = [_make_result("dns", 50, findings)]
        html = generate_html_report(results, 50.0)
        assert "2 findings" in html

    def test_single_module_multiple_findings(self):
        findings = [
            _make_finding(title="Issue One", threat_level=ThreatLevel.HIGH),
            _make_finding(title="Issue Two", threat_level=ThreatLevel.LOW),
            _make_finding(title="Issue Three", threat_level=ThreatLevel.INFO),
        ]
        results = [_make_result("dns", 45, findings)]
        html = generate_html_report(results, 45.0)
        assert "Issue One" in html
        assert "Issue Two" in html
        assert "Issue Three" in html


class TestThreatBadges:
    """Severity badge rendering."""

    def test_all_threat_levels_present(self):
        findings = [
            _make_finding(threat_level=ThreatLevel.CRITICAL),
            _make_finding(title="High issue", threat_level=ThreatLevel.HIGH),
            _make_finding(title="Medium issue", threat_level=ThreatLevel.MEDIUM),
            _make_finding(title="Low issue", threat_level=ThreatLevel.LOW),
            _make_finding(title="Info item", threat_level=ThreatLevel.INFO),
        ]
        results = [_make_result("test", 30, findings)]
        html = generate_html_report(results, 30.0)
        assert "CRITICAL" in html
        assert "HIGH" in html
        assert "MEDIUM" in html
        assert "LOW" in html
        assert "INFO" in html


class TestScoreColors:
    """Score colors match label levels."""

    def test_excellent_green(self):
        html = generate_html_report([], 95.0)
        assert "#1a7f37" in html

    def test_poor_red(self):
        html = generate_html_report([], 25.0)
        assert "#cf222e" in html

    def test_label_moderate(self):
        html = generate_html_report([], 55.0)
        assert "Moderate" in html

    def test_label_poor(self):
        html = generate_html_report([], 35.0)
        assert "Poor" in html

    def test_label_critical(self):
        html = generate_html_report([], 15.0)
        assert "Critical" in html


class TestXssSafety:
    """All user-provided strings are HTML-escaped."""

    def test_escapes_module_name(self):
        results = [_make_result('<script>alert("xss")</script>', 50)]
        html = generate_html_report(results, 50.0)
        assert '<script>alert("xss")</script>' not in html
        assert "&lt;script&gt;alert(" in html

    def test_escapes_finding_title(self):
        finding = _make_finding(title='<img onerror="alert(1)">')
        results = [_make_result("test", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert 'onerror="alert(1)"' not in html
        assert "&lt;img" in html

    def test_escapes_finding_description(self):
        finding = _make_finding(description="<script>steal()</script>")
        results = [_make_result("test", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert "<script>steal()</script>" not in html

    def test_escapes_remediation(self):
        finding = _make_finding(remediation='<a href="javascript:void(0)">click</a>')
        results = [_make_result("test", 50, [finding])]
        html = generate_html_report(results, 50.0)
        assert 'href="javascript:' not in html
